//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfflineWebsiteViewer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OfflineWebsiteViewer.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t open project &quot;{0}&quot;.
        /// </summary>
        public static string ErrorCantOpenProject {
            get {
                return ResourceManager.GetString("ErrorCantOpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string LoggingClearAll {
            get {
                return ResourceManager.GetString("LoggingClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show output from:.
        /// </summary>
        public static string LoggingShowOutputFrom {
            get {
                return ResourceManager.GetString("LoggingShowOutputFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string LoggingTitle {
            get {
                return ResourceManager.GetString("LoggingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Index.
        /// </summary>
        public static string MenuClearIndex {
            get {
                return ResourceManager.GetString("MenuClearIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Index.
        /// </summary>
        public static string MenuCreateIndex {
            get {
                return ResourceManager.GetString("MenuCreateIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string MenuIndex {
            get {
                return ResourceManager.GetString("MenuIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open log.
        /// </summary>
        public static string MenuOpenLog {
            get {
                return ResourceManager.GetString("MenuOpenLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string MenuTools {
            get {
                return ResourceManager.GetString("MenuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear recent projects.
        /// </summary>
        public static string MenuToolsClearRecent {
            get {
                return ResourceManager.GetString("MenuToolsClearRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Dev Tools.
        /// </summary>
        public static string MenuToolsDevTools {
            get {
                return ResourceManager.GetString("MenuToolsDevTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No projects on removable drives found..
        /// </summary>
        public static string NoProjectOnRemovableDrivesFound {
            get {
                return ResourceManager.GetString("NoProjectOnRemovableDrivesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open archive.
        /// </summary>
        public static string OpenArchive {
            get {
                return ResourceManager.GetString("OpenArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently opened.
        /// </summary>
        public static string RecentOpened {
            get {
                return ResourceManager.GetString("RecentOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} pages in index.
        /// </summary>
        public static string StatusIndexCount {
            get {
                return ResourceManager.GetString("StatusIndexCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building search index.
        /// </summary>
        public static string StatusIndexCreating {
            get {
                return ResourceManager.GetString("StatusIndexCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index build finished.
        /// </summary>
        public static string StatusIndexFinished {
            get {
                return ResourceManager.GetString("StatusIndexFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} results matching query &quot;{1}&quot;.
        /// </summary>
        public static string StatusIndexFound {
            get {
                return ResourceManager.GetString("StatusIndexFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened project {0} .
        /// </summary>
        public static string StatusOpened {
            get {
                return ResourceManager.GetString("StatusOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for &quot;{0}&quot;....
        /// </summary>
        public static string StatusSearching {
            get {
                return ResourceManager.GetString("StatusSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
